{% set name = "appmode" %}
{% set version = "0.4.0" %}
{% set sha256 = "d0c017dcebe7c3e8bbf7b2388388b963ee38fd48a36cea7e80bb8636a3eececa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: appmode-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/appmode/appmode-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # noarch: python # suffers from https://github.com/conda/conda-build/issues/2357
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - notebook >=5
  run:
    - python
    - notebook >=5

test:
  imports:
    - appmode

about:
  home: https://github.com/oschuett/appmode
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A Jupyter extensions that turns notebooks into web applications.'

extra:
  recipe-maintainers:
    - oschuett
