{% set name = "appmode" %}
{% set version = "0.2.0" %}
{% set sha256 = "e0703e3ee2a616db79c1f7b465dab05385e41a7b6d5d6ad9f9aaa2b4a283b08d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: appmode-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/appmode/appmode-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # noarch: python # suffers from https://github.com/conda/conda-build/issues/2357
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - notebook >=5
  run:
    - python
    - notebook >=5

test:
  imports:
    - appmode

about:
  home: https://github.com/oschuett/appmode
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A Jupyter extensions that turns notebooks into web applications.'

extra:
  recipe-maintainers:
    - oschuett
