travis:
  secure:
    BINSTAR_TOKEN: Li/s3ndqJQn2/W44zXxNjnXdw2CdFVfGNsQQDLeJo6SuMzSl8d0mQVEzNNLpajOfOQSsjIogQPDJ8Vt03x3hoc2JH0KKfEcSsbeREFmWHJBz6DElnz55UoN9aS06N9zSIWHiAW7nd5mdGYcnt9xoX6vbsFBGAljs/MgcDDdG7iNyeOVFnYR/P5bCjHCfRiFkh3fsR+yjToMtKdnliKQnEfS0N8/rLYP93G5U53teeeO4oU4XRIXSaWrbIs6G0cyPoeF/+w+D5EDRqM4DzWUAkkNNiFQGOFW8Y4/D2v4ydfa1a2pjygv45lADAlIzQr000D4Gx4EKtpvU6jj8vcRjwqONc9gfzau2VvfVZajUGYYWmMi6zhgcjFbRXWieDnjSemvXdIDErphP+Noa+KnJSqq/wrQLIlPNvG+WU8e/QGN5PmH9E3P9CANsHjtvHKXPiCRT4DTvlMzKVX1r5IXJWDK4S4IFNe3M+sqrohiQGTrL7oA7yEhraLEBmI//F/Jhd3QaeEEEOX51xCSjMBuCjo9rg6ZxXIHAeh4I/SNX8vxdHJ/a2ZqlAnoMLmWiGcmw+u60nFFBJu75cbDMNKtPgiP07oyJ2EpikJ2uKYpjhh1FqtuwR0zBGkzaulb4C+/H8fjP03Z1Tc/ObqdB/UwaYZT3tcs2xmx7YNht4SQoQm4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
