travis:
  secure:
    BINSTAR_TOKEN: T0m/mYoxQAwU6NZwB5eCav4U+X/d1nQgJugk2AApojVMROpeX4NXqWsPsrQ50HmvlvhuG+xdRce72FSqMFmJSqtCgXPFyvhyDJ4xnvlTtVaDhozaGfAqbb4ghWQtxy5La7/t0g3HJ/ocxiDqEZdBKom5j+0QcrwRiwHxg3L1LLCj5inabYGTPT0mjAzeDiQYDNEI2khmme+NVlN/Kn1W0WTs4lziNBJJ8DRx3AmgUrL+I2xAc75cbxq61+BtR8PZUVm8kICQNL9Dw8wVd0jZ4gZ/4NOBnbf7oFwDjSutwbk7psDIwCDvpfonH6zqx3xH/S9FYHpNDQoDOcuQys+y0VWh+n7c5Lgi1z8hN3DJYr2okrUEj9WckEJjhwhYU78nF1Q2D95lFjdYqODIHZZuZ57MWJ9lIa5/teG6Mr20K3ZBXHcygwQwEysxX70mybur6SSPH6TNpUEVQ6ZfE0lFDz7irEbPNYlWX+qn6NQdllta6o7UphTZKm8mOG7NLFGq43jsPDzTpl/7DQcC4NE2Q9umoG14uhvZqsH9koaCbYOkFjZu24kxMloPOo675aQIULxG8fUzKciBJp89pSTh3VCIueq3i5voHcIVe6EoLPYDq6F9JYp2WQJQGMAjmz13eYtS/0cm+BX738CYHdiWIVeKCFJJK8+Fqr4PId/eaCI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
